name: Bug Report
description: File a bug report
title: "[A short descriptive title]"
body:
  - type: input
    id: contact
    attributes:
      label: What isn't working as expected on the website?
      placeholder: When I add new information to an existing record in the database, I can only see this new information in the website’s backend. I can’t see it in the search results.
    validations:
      required: true
  - type: textarea
    attributes:
      label: If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.
      description: If you see an error message, please use the copy details button to copy and paste the information into the bug report.
    validations:
      required: true
  - type: input
    attributes:
      label: What is the URL of the page where you encountered the bug?
      description: If you unable to share the full URL, please include as much of the URL as possible. Type NA if not applicable.
      placeholder: https://dhil.lib.sfu.ca/my-project/person/9
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps did you take before your encountered the bug?
      description: "Please provide information such as: how you got to the error, how often the errors occurs, what button you've clicked, or what was typed."
      value: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct and have read the Guidelines for Submitting Issues.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
